# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install -r requirements-dev.txt

install:
  - python setup.py install
  - pip install codecov==2.0.15

script:
  - flake8 --statistics crimson tests setup.py
  - mypy crimson tests setup.py
  - py.test --cov --cov-config=.coveragerc --cov-report=term-missing tests crimson

after_success:
  - codecov
