# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

before_install:
  - pip install -r requirements-dev.txt

install:
  - python setup.py install
  - pip install codecov==2.0.5

script:
  - py.test --cov --cov-config .coveragerc --flake8 tests crimson

after_success:
  - codecov
